
class Autogenerated {
  int status;
  int totalnum;
  List<Lists> list;

  Autogenerated({this.status, this.totalnum, this.list});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['Status'];
    totalnum = json['totalnum'];
    if (json['list'] != null) {
      list = new List<Lists>();
      json['list'].forEach((v) {
        list.add(new Lists.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Status'] = this.status;
    data['totalnum'] = this.totalnum;
    if (this.list != null) {
      data['list'] = this.list.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Lists {
  int dictionaryDetailId;
  int dictionaryMainId;
  String dictionaryKey;
  String dictionaryValue;
  int dictionaryCreatDate;
  bool checkBox;
  Lists(
      {this.dictionaryDetailId,
      this.dictionaryMainId,
      this.dictionaryKey,
      this.dictionaryValue,
      this.dictionaryCreatDate,
      this.checkBox});

  Lists.fromJson(Map<String, dynamic> json) {
    dictionaryDetailId = json['DictionaryDetailId'];
    dictionaryMainId = json['DictionaryMainId'];
    dictionaryKey = json['DictionaryKey'];
    dictionaryValue = json['DictionaryValue'];
    dictionaryCreatDate = json['DictionaryCreatDate'];
    checkBox = false;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['DictionaryDetailId'] = this.dictionaryDetailId;
    data['DictionaryMainId'] = this.dictionaryMainId;
    data['DictionaryKey'] = this.dictionaryKey;
    data['DictionaryValue'] = this.dictionaryValue;
    data['DictionaryCreatDate'] = this.dictionaryCreatDate;
    data['checkBox'] = this.checkBox;
    return data;
  }
}